stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps: 
      - src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/interim
  
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/interim/train_processed.csv
      - params.yaml
    params:
      - feature_engineering.max_features
      - feature_engineering.ngram_range
      - feature_engineering.custom_features_batch_size
    outs:
      - data/processed/custom_features_train.csv
      - data/processed/X_train_BOW_custom.pkl
      - data/processed/y_train.pkl
      - data/processed/bow_vectorizer.pkl
  
  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/processed/X_train_BOW_custom.pkl
      - data/processed/y_train.pkl
      - params.yaml
    outs:
      - models/lgbm_reddit_sentiment.pkl
  
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - src/model/model_evaluation.py
    - data/interim/train_processed.csv
    - data/processed/X_train_BOW_custom.pkl
    - models/lgbm_reddit_sentiment.pkl
    outs:
    - reports/classification_report.json
    - reports/confusion_matrix_test_set.png
  
